FROM node:20-slim

ARG VITE_OPENAI_API_KEY
ARG VITE_BACKEND_API_URL

ENV VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
ENV VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}

WORKDIR /app

RUN rm -rf node_modules

COPY package*.json ./

RUN npm install --no-optional

COPY . .

ENV PATH=/app/node_modules/.bin:$PATH

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]