FROM php:8.2-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . /var/www

RUN if [ -f composer.json ]; then composer install; else echo "composer.json not found, skipping composer install"; fi

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
